services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ../.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pet_data:/var/lib/postgresql

  migration:
    image: liquibase/liquibase:4.23
    working_dir: /liquibase/changelog
    env_file:
      - ../.env
    volumes:
      - ./../changelog:/liquibase/changelog
    command: >
      liquibase --changeLogFile=0.0.1_create_schema.xml --url=jdbc:postgresql://db:${DB_PORT}/${DB_NAME} --username=${DB_USERNAME} --password=${DB_PASSWORD}  update


volumes:
  pet_data: